### ISSUE TITLE
Using a custom puid:guid with docker doesn't work

### ISSUE THREAD

**Issue by marouamghar** [go-vikunja/api#69]
### Description

Wen specifying the puid:guid with the user field with docker, both the api and the frontend don't deploy
The api starts failing with the error :
`groupmod: /etc/group.8: Permission denied`
The frontend fails with the error :
`sed: can't create temp file '/usr/share/nginx/html/index.htmlXXXXXX': Permission denied`

### Vikunja Frontend Version

latest

### Vikunja API Version

latest

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Can you share the full command you used?

**Comment by kolaente** [comment]
That won't work because Vikunja starts as root, changes the permissions and then drops its privileges. You can use the `PUID` and `PGID` env variables to change the uid and gid of the user running Vikunja, as documented [here](https://vikunja.io/docs/install-backend/#setting-user-and-group-id-of-the-user-running-vikunja).

The frontend container does not support changing the user id as it runs as an unprivileged user and does not expose anything (volumes etc) to the host which would require different permissions.

**Comment by marouamghar** [comment]
> That won't work because Vikunja starts as root, changes the permissions and then drops its privileges. You can use the `PUID` and `PGID` env variables to change the uid and gid of the user running Vikunja, as documented [here](https://vikunja.io/docs/install-backend/#setting-user-and-group-id-of-the-user-running-vikunja).
> 
> The frontend container does not support changing the user id as it runs as an unprivileged user and does not expose anything (volumes etc) to the host which would require different permissions.

Thanks for the link, I missed it.
For the frontend container, yeah I arrived to that conclusion and didn't post the same issue on the other repo, but forgot to clean it here.
